# SourceSyncSDK/Podfile
platform :ios, '14.0'
use_frameworks!

# Specify the Xcode project explicitly
project 'SourceSyncSDK.xcodeproj'

target 'SourceSyncSDK' do
  # DivKit dependencies
  pod 'DivKit', '~> 32.1.0'
  pod 'DivKitExtensions', '~> 32.1.0'
end

# If you have a test target
target 'SourceSyncSDKTests' do
  pod 'DivKit', '~> 32.1.0'
  pod 'DivKitExtensions', '~> 32.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Basic deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      
      # UNIVERSAL BINARY SUPPORT - Support all architectures
      config.build_settings['ARCHS'] = '$(ARCHS_STANDARD)'
      config.build_settings['VALID_ARCHS'] = 'arm64 x86_64 arm64e'
      
      # NO EXCLUSIONS - Support all platforms
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphoneos*]')
      config.build_settings['EXCLUDED_ARCHS'] = ''
      
      # Build for all active architectures
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      
      # Enable universal binaries
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
      # Ensure compatibility across different Xcode versions
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      config.build_settings['DEFINES_MODULE'] = 'YES'
      
      # Support both Intel and Apple Silicon simulators
      if config.name == 'Debug'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end
      
    end
  end
end