# Podfile for MobileDemo
# Recreated after git clean incident

platform :ios, '13.0'
use_frameworks!

target 'MobileDemo' do
  
   pod 'SourceSyncSDK', :path => '../SourceSyncSDK'
#  pod 'SourceSyncSDK', '0.3.14'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end
end
